[workspace]
authors = ["Markus Groissböck <markus.groissboeck@gmx.at>"]
channels = ["conda-forge", "bioconda", "gurobi"]
name = "pypsa-earth"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.12"
pip = "*"
pypsa = ">=0.25.1,<=0.30.3"
atlite = ">=0.4.1"
dask = "*"
powerplantmatching = ">=0.8"
earth-osm = ">=2.3.post1"
xlrd = "*"
openpyxl = "*"
seaborn = "*"
snakemake-minimal = "<8"
memory_profiler = "*"
"ruamel.yaml" = "<=0.17.26"
pytables = "*"
pyscipopt = "*"
lxml = "*"
numpy = "<2"
pandas = "*"
geopandas = ">=1"
fiona = ">=1.10"
xarray = ">=2023.11.0,<=2025.1.2"
netcdf4 = "*"
libgdal-netcdf = "*"
networkx = "*"
scipy = "<1.16"
pydoe2 = "*"
shapely = "!=2.0.4"
pre-commit = "*"
matplotlib = "*"
reverse-geocode = "*"
country_converter = "*"
pyogrio = "*"
numba = "*"
py7zr = "*"
tsam = ">=1.1.0"
fake-useragent = "*"
chaospy = "*"
geopy = "*"
tqdm = "*"
pytz = "*"
ipykernel = "*"
ipython = "*"
jupyterlab = "*"
cartopy = "*"
rasterio = "*"
rioxarray = "*"
geoviews = "*"
hvplot = "*"
graphviz = "*"
contextily = "*"
glpk = "*"
gurobi = "*"
rich = "*"
highspy = "==1.14.0"
openjdk = "17.*"

[pypi-dependencies]
currencyconverter = "*"
googledrivedownloader = ">=1.1"

[activation]
scripts = ["pixi/activate.sh"]
